### ISSUE TITLE
adsense auto ads dont display on mobile browsers

### ISSUE THREAD

**Issue by TheunisKotze** [eisberg-labs/react-components#11]
Hi, this isn't necessarily an issue with your library, but I haven't been able to get the ads to display on mobile. They display on desktop. Do you have any insight as to why this may be the case? Does this work for you?

No errors, just this warning in console:
"AdSense head tag doesn't support data-nscript attribute."

Thanks!

**Comment by amarjanica** [comment]
Hi, thanks for reporting. 

That attribute is added due to usage of next/script instead of plain script, and adsense doesn't seem to like it. 
It's just a warning in the console, auto ads show up both on mobile and desktop.

Try the 3.1.1 version, console warning shouldn't appear

**Comment by TheunisKotze** [comment]
Hi thanks so much for the response, sorry to open this again. For some reason, on my site, auto ads only display on desktop - the side banner ads. The ones that should display in the page, between content, don't. There are no other errors. Manually placing ads does work. Do you have any idea what could be the issue? Could it have something to do with hydration? Do auto inline ads work for you?

**Comment by amarjanica** [comment]
I don't think it's related to hydration, could be a  lack of traffic on your site, or maybe above the fold content.
One of my websites https://www.najsalon.com/saloni/friz-frizerski-salon shows inline ads in mobile, 
and that one I still didn't update with latest fix.
I haven't fully tested the AdUnit component, but autoads should show up fine.

**Comment by TheunisKotze** [comment]
Okay thanks for the feedback just strange that I always see plenty of the other types of ads but no inline ones. The site gets a ton of traffic. Anyway, maybe I should just give it more time. Thanks again
